# Generated by Django 5.1.2 on 2024-10-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiPharmaapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
