# Generated by Django 5.1.2 on 2024-10-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiPharmaapp', '0004_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
