# Generated by Django 5.1.2 on 2024-11-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiPharmaapp', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
